name: chandrima_real_estate
version: 1.0.0+2
publish_to: 'none'
description: "A new Flutter project."
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.3
  http: ^1.2.1
  image_picker: ^1.1.2
  intl:
  shimmer: ^3.0.0
  pull_to_refresh_flutter3: ^2.0.2
  flutter_tabler_icons:
  url_launcher: ^6.0.3
  share_plus: ^10.1.3
  fluttertoast: ^8.2.10
  curved_navigation_bar: ^1.0.6



dev_dependencies:
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  rename_app: ^1.6.1


flutter_launcher_icons:
  image_path_ios: "assets/images/app_logo.png"
  image_path_android: "assets/images/app_logo.png"
  ios: true
  android: true
  adaptive_icon_background: "#ffffff"
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/db/
    - assets/images/


