name: chandrima_real_estate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.2
  http: ^1.2.1
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.10
  shimmer: ^3.0.0
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  flutter_tabler_icons: ^1.43.0
  intl: ^0.20.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/